# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  HELM_EXPERIMENTAL_OCI: 1
  projectName: app-one-api

stages:
- stage: Build
  displayName: Build Helm
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: HelmInstaller@0
      inputs:
        helmVersion: '3.4.1'
    - bash: |
        helm lint ./$(projectName)
      failOnStderr: true
      displayName: 'Helm lint'
    - bash: |
        helm lint ./$(projectName)
      failOnStderr: true
      displayName: 'Helm lint'
    - bash: |
        HELM_VERSION = $(cat ./$(projectName)/Chart.yaml | awk '/version:/ {print $2}')
        echo "##vso[task.setvariable variable=HELM_VERSION]$HELM_VERSION"
        echo Helm version $HELM_VERSION
      failOnStderr: true
      displayName: 'Extract Helm Chat version'
    - task: HelmDeploy@0
      displayName: Helm package
      inputs:
        command: package
        chartPath: ./$(projectName)
        destination: $(Build.ArtifactStagingDirectory)
      

